---
- name: Install required system packages
  become: true
  ansible.builtin.yum:
    name:
      - cri-o
      - cri-tools
    state: present
    enablerepo: microshift-deps-rpms
  notify: Restart crio

- name: Use only ipv4
  become: true
  ansible.builtin.copy:
    src: crio-bridge.conf
    dest: /etc/cni/net.d/100-crio-bridge.conf
    mode: "0644"
  notify: Restart crio

- name: Apply container policy from crc
  become: true
  ansible.builtin.copy:
    src: policy.json
    dest: /etc/containers/policy.json
    mode: "0644"
  notify: Restart crio
  when: overwrite_container_policy

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
